### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by conorlawton**

### CODE REVIEW

**Comment by lexisother** [comment]
~~`yarn prettier --write '**/*.ts'` please.~~

Nevermind, this changes too much and is outside of the PR scope.

**Comment by dmitmel** [comment]
@conorlawton Can you please run the formatter over your changes?

**Comment by dmitmel** [comment]
Oh no

**Comment by dmitmel** [comment]
@conorlawton Please do `git push --force origin master` from your machine and then reopen this PR

**Comment by dmitmel** [comment]
Well, by reopen I meant to reopen this one but whatever, doesn't matter

**Pull request closed without merging**
